version: '3.8'

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - proxynet
    environment:
      SSL_POLICY: Mozilla-Modern

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: ashley.malone@gmail.com
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - proxynet
    restart: always
    depends_on:
      - nginx-proxy

networks:
  proxynet:
    name: mynetwork