version: '2'

services:
  api:
    image: frozenpixel/celletech-api:dev
    container_name: celletech_api_prod
    expose:
      - 80
      - 443
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: api.a6design.net
      LETSENCRYPT_HOST: api.a6design.net
      VIRTUAL_PORT: 8000
    networks:
      - saleor-backend-tier
      - my-proxy-net
    depends_on:
      - redis
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file: prod.env
  
  storefront:
    image: frozenpixel/celletech-storefront:dev
    container_name: celletech_storefront_prod
    expose:
      - 80
      - 443
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: cell.a6design.net
      LETSENCRYPT_HOST: cell.a6design.net
      VIRTUAL_PORT: 443
    networks:
      - my-proxy-net

  dashboard:
    image: frozenpixel/celletech-dashboard:dev
    container_name: celletech_dashboard_prod
    expose:
      - 80
      - 443
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: dashboard.a6design.net
      LETSENCRYPT_HOST: dashboard.a6design.net
      VIRTUAL_PORT: 443
    networks:
      - my-proxy-net

  redis:
    image: library/redis:5.0-alpine
    expose:
      - 6379
    working_dir: /data
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    image: frozenpixel/celletech-api:dev
    container_name: celletech_worker_prod
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - redis
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file: prod.env
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info

volumes:
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
  my-proxy-net:
    external:
      name: mynetwork