version: '2'

services:
  api:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile.prod
      args:
        STATIC_URL: '/static/'
    image: celldev-api:dev
    expose:
      - 80
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: api.a6design.net
      VIRTUAL_PROTO: uwsgi
      VIRTUAL_PORT: 8000
    networks:
      - saleor-backend-tier
      - my-proxy-net
    depends_on:
      - redis
      - jaeger
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file: prod.env
  
  storefront:
    build:
      context: ./saleor-storefront
      dockerfile: ./Dockerfile
    image: celldev-storefront:dev
    expose:
      - 80
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: cell.a6design.net
    networks:
      - my-proxy-net

  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile
    image: celldev-dashboard:dev
    expose:
      - 80
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: dashboard.a6design.net
    networks:
      - my-proxy-net

  redis:
    image: library/redis:5.0-alpine
    expose:
      - 6379
    working_dir: /data
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  worker:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    depends_on:
      - redis
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    env_file: prod.env
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    expose:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 14268
      - 9411
    restart: unless-stopped
    networks:
      - saleor-backend-tier

volumes:
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
  my-proxy-net:
    external:
      name: mynetwork